course_name: CSE589
course_description: This course explores wireless technologies, mobile networking,
  and mobile sensing with applications in IoT, signal processing, and human-computer
  interaction. Students will engage with cutting-edge research in mobile computing
  systems.
course_semester: Spring 2026
baseurl: /CSE589_UB_SP26
url: https://xieyaxiongfly.github.io
schoolname: University at Buffalo, SUNY
schoolurl: https://buffalo.edu
logo_path: /_images/UB_logo.jpg
logo_width: 75
address: 'Computer Science and Engineering

  University at Buffalo, SUNY

  Buffalo, NY, USA

  '
markdown: kramdown
permalink: blog/:year/:month/:title
excerpt_separator: <!--more-->
include:
- _images
- _css
exclude:
- develop
dateformat: '%m/%d/%Y'
future: true
collections:
  events:
    output: true
  lectures:
    output: true
  assignments:
    output: true
  announcements:
    output: false
defaults:
- scope:
    path: ''
    type: assignments
  values:
    layout: assignment
